export const getPlayerComp = (shootingPercentage: number) => {
  // percentage 0 to 100

  const playerCompMap = new Map([
    [0, "Shaquille O'Neal"],
    [1, "Shaquille O'Neal"],
    [2, "Shaquille O'Neal"],
    [3, "Shaquille O'Neal"],
    [4, "Shaquille O'Neal"],
    [5, "Shaquille O'Neal"],
    [6, "Shaquille O'Neal"],
    [7, "Shaquille O'Neal"],
    [8, "Shaquille O'Neal"],
    [9, "Shaquille O'Neal"],
    [10, "Shaquille O'Neal"],
    [11, "Shaquille O'Neal"],
    [12, "Shaquille O'Neal"],
    [13, "Shaquille O'Neal"],
    [14, "Shaquille O'Neal"],
    [15, "Shaquille O'Neal"],
    [16, "Shaquille O'Neal"],
    [17, "Shaquille O'Neal"],
    [18, "Shaquille O'Neal"],
    [19, "Shaquille O'Neal"],

    [20, 'Dwight Howard'],
    [21, 'DeAndre Jordan'],
    [22, 'Andre Drummond'],
    [23, 'Clint Capela'],
    [24, 'Rudy Gobert'],
    [25, 'Steven Adams'],
    [26, 'Kevon Looney'],
    [27, 'Jakob Poeltl'],
    [28, 'Mitchell Robinson'],
    [29, 'Jarrett Allen'],

    [30, 'Draymond Green'],
    [31, 'Julius Randle'],
    [32, 'Aaron Gordon'],
    [33, 'Pascal Siakam'],
    [34, 'Bam Adebayo'],
    [35, 'Giannis Antetokounmpo'],
    [36, 'Zion Williamson'],
    [37, 'LeBron James'],
    [38, 'Jimmy Butler'],
    [39, 'DeMar DeRozan'],

    [40, 'Russell Westbrook'],
    [41, 'RJ Barrett'],
    [42, 'Josh Giddey'],
    [43, 'Scottie Barnes'],
    [44, 'Jonathan Kuminga'],
    [45, 'Jaylen Brown'],
    [46, 'Anthony Edwards'],
    [47, 'Donovan Mitchell'],
    [48, 'Darius Garland'],
    [49, 'CJ McCollum'],

    [50, 'Tyrese Haliburton'],
    [51, 'Trae Young'],
    [52, 'Damian Lillard'],
    [53, 'Kyrie Irving'],
    [54, 'Fred VanVleet'],
    [55, 'Jordan Poole'],
    [56, 'Tyler Herro'],
    [57, 'Desmond Bane'],
    [58, 'Zach LaVine'],
    [59, 'Bradley Beal'],

    [60, 'Jamal Murray'],
    [61, 'CJ McCollum'],
    [62, 'Khris Middleton'],
    [63, 'Buddy Hield'],
    [64, 'Desmond Bane'],
    [65, 'Devin Booker'],
    [66, 'Damian Lillard'],
    [67, 'Kyrie Irving'],
    [68, 'Devin Booker'],
    [69, 'Damian Lillard'],

    [70, 'Klay Thompson'],
    [71, 'Klay Thompson'],
    [72, 'Ray Allen'],
    [73, 'Reggie Miller'],
    [74, 'Peja Stojakovic'],
    [75, 'Larry Bird'],
    [76, 'Steve Nash'],
    [77, 'Dirk Nowitzki'],
    [78, 'Kevin Durant'],
    [79, 'Ray Allen'],
    [80, 'Reggie Miller'],

    [81, 'Stephen Curry'],
    [82, 'Stephen Curry'],
    [83, 'Stephen Curry'],
    [84, 'Stephen Curry'],
    [85, 'Stephen Curry'],
    [86, 'Stephen Curry'],
    [87, 'Stephen Curry'],
    [88, 'Stephen Curry'],
    [89, 'Stephen Curry'],
    [90, 'Stephen Curry'],
    [91, 'Stephen Curry'],
    [92, 'Stephen Curry'],
    [93, 'Stephen Curry'],
    [94, 'Stephen Curry'],
    [95, 'Stephen Curry'],
    [96, 'Stephen Curry'],
    [97, 'Stephen Curry'],
    [98, 'Stephen Curry'],
    [99, 'Stephen Curry'],
    [100, 'Stephen Curry'],
  ])

  const comp = playerCompMap.get(Math.round(shootingPercentage))
  return comp || "Shaquille O'Neal"
}
